### ISSUE TITLE
Tiles support

### ISSUE THREAD

**Issue by marceloabner** [Mr-Byte/fast-flip#1]
Could you update this module to do the same thing for tiles? This would be helpfull too. And maybe do a 360° step-by-step rotation too.

Thanks

**Comment by Mr-Byte** [comment]
Flipping tiles will definitely be in the next release when I get the chance to work on it. I'll also include the ability to do vertical flipping (probably more useful for tiles).

Thanks for the suggestion!

**Comment by Mr-Byte** [comment]
v1.1.0 has support for flipping tiles and introduced `Shift+F` to flip tiles and tokens vertically.
