### ISSUE TITLE
Foundry v10 incompatible, sorta

### ISSUE THREAD

**Issue by shecrio** [Mr-Byte/fast-flip#5]
You can flip... once. But not flip back.

commons.js:1250 Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1239)
    at Function._logV10CompatibilityWarning (commons.js:6143)
    at Actor5e.get data [as data] (commons.js:6043)
    at Function.UpdateToken (aura.js:129)
    at Function.UpdateAllTokens (aura.js:111)
    at Function.MainAura (aura.js:42)
    at CollateAuras (collateAuras.js:73)
logCompatibilityWarning @ commons.js:1250
_logV10CompatibilityWarning @ commons.js:6143
get data @ commons.js:6043
UpdateToken @ aura.js:129
UpdateAllTokens @ aura.js:111
MainAura @ aura.js:42
CollateAuras @ collateAuras.js:73
async function (async)
CollateAuras @ collateAuras.js:60
(anonymous) @ AAhooks.js:22
#call @ foundry.js:688
callAll @ foundry.js:645
setupGame @ foundry.js:7769
async function (async)
setupGame @ foundry.js:7728
_initializeGameView @ foundry.js:8820
_initializeView @ foundry.js:8796
initialize @ foundry.js:7630
async function (async)
initialize @ foundry.js:7621
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:796
async function (async)
🎁libWrapperInit @ libWrapper-api.js:786
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:78537
async function (async)
window.addEventListener.once @ foundry.js:78536
commons.js:1250 Error: You are accessing Actor5e#data which has been migrated to Actor5e#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1239)
    at Function._logDataFieldMigration (commons.js:6132)
    at Object.get (commons.js:6096)
    at Function.UpdateToken (aura.js:129)
    at Function.UpdateAllTokens (aura.js:111)
    at Function.MainAura (aura.js:42)
    at CollateAuras (collateAuras.js:73)
logCompatibilityWarning @ commons.js:1250
_logDataFieldMigration @ commons.js:6132
get @ commons.js:6096
UpdateToken @ aura.js:129
UpdateAllTokens @ aura.js:111
MainAura @ aura.js:42
CollateAuras @ collateAuras.js:73
async function (async)
CollateAuras @ collateAuras.js:60
(anonymous) @ AAhooks.js:22
#call @ foundry.js:688
callAll @ foundry.js:645
setupGame @ foundry.js:7769
async function (async)
setupGame @ foundry.js:7728
_initializeGameView @ foundry.js:8820
_initializeView @ foundry.js:8796
initialize @ foundry.js:7630
async function (async)
initialize @ foundry.js:7621
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:796
async function (async)
🎁libWrapperInit @ libWrapper-api.js:786
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:78537
async function (async)
window.addEventListener.once @ foundry.js:78536

**Comment by Mr-Byte** [comment]
Thanks for the report.  There's a new V10 version out (just released).  I had the fix done last weekend, but due to time constraints I can only work on this project during the weekends so I couldn't get around to releasing it until this weekend.
