### ISSUE TITLE
V10: Issue with rapid flipping

### ISSUE THREAD

**Issue by Ross-Davidson-HW** [Mr-Byte/fast-flip#6]
V10 added a new animation when the token flips over. However if you press the flip key over and over too fast, the token begins to skew more and more until it becomes just a narrow line in the middle of its space, as shown in this image.

![image](https://user-images.githubusercontent.com/50166106/189786172-78ddf0d7-5469-485e-912f-5455247e23cb.png)

**Comment by Mr-Byte** [comment]
Hi there,

I was able to reproduce this myself, but this appears to be an issue with how Foundry now animates flipping tokens more than an issue with Fast Flip itself.  I don't see a way to easily disable the animations within Foundry that Fast Flip could possibly use to prevent this from happening.  It may take a while to find an appropriate fix.

**Comment by seanms1991** [comment]
There is a module similar to this one that seems to modify the speed of the flipping animation. Perhaps you could make the animation faster or disable it using the same method Token Mirror Button is using: https://github.com/MAClavell/Token-Mirror-Button/

**Comment by Mr-Byte** [comment]
Hi,

I just released v3.1.0 for V10 that should fix this. It allows you to configure animations and will prevent you from further flipping tokens while they're being animated.

I've spent some time testing this with both PF2e and 5e and everything seems to work as expected now.
