### ISSUE TITLE
No Flip V10 PF2E

### ISSUE THREAD

**Issue by InstantZzz** [Mr-Byte/fast-flip#7]
Hi, 

I find that I am unable to flip my tokens in V10.
More specifically, I am on Pathfinder 2E v4.0.6 and Foundry v10.285 with Fast Flip 3.0.0
I have tried using both the keybinds and the buttons when you have a token selected. Neither of these work.
The AFK button works though.

I have tried this module in my current game and a new game I created to test if there was some weird conflict with my other modules and in both games I am unable to flip my tokens.

**Comment by Mr-Byte** [comment]
Hi,

I was able to confirm that this is indeed broken in PF2e, but the problem doesn't seem to be on Fast Flip's side.  While testing this I was unable to reproduce any errors and I also tried using the Mirror Token check boxes in the token's settings under Appearance, and it also had no effect.

![image](https://user-images.githubusercontent.com/2321210/190832714-988b113e-7cb8-4907-ad14-938ca7e32d90.png)

This is likely an issue with the PF2e system itself.

**Comment by InstantZzz** [comment]
Alright, thank you very much for the update. I honestly didn't think to check the _mirror image_ buttons as I had gotten so used to Fast Flip. I guess I'll just have to wait and hope the issue to resolve itself or leave a message with their team asking about the mirror feature.

**Comment by InstantZzz** [comment]
Hi again, within the last 24 hours, Pathfinder 2nd Edition updated to V4.1.0. which fixed the _mirror image_ function.
I re-enabled Fast-Flip which now works - sorta. Fast-Flip now allows me to mirror my tokens both horizontally and vertically but clicking the Flip button a second time does not return the token to its original position. 
(I can flip the token once each way but I cannot flip it back to its original position.)

**Comment by Mr-Byte** [comment]
Thanks for the update! Since I'm in process of converting my own campaigns
over to PF2e I'll take a deeper look at this and see what I can do.

**Comment by Mr-Byte** [comment]
Hi there, I've released v3.1.0 which should fix this for you.  I've tested this multiple times using the latest PF2e and I'm unable to reproduce this at this time.
